- name: Create Azure VM
  vars:
    rg_name: ansibleVMTest
    user_name: azureuser
    ssh_pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      location: northeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ rg_name }}"
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ rg_name }}"
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ rg_name }}"
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ rg_name }}"
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ rg_name }}"
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: "{{ user_name }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_pubkey }}"
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
  - name: Save user_name and public ip to file
    copy:
      dest: "./inventory"
      content: |
        test_vm ansible_user={{ user_name }} ansible_host={{ output_ip_address.state.ip_address }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'